version: "3"
services:
  frontend:
    build:
      context: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app

  backend:
    build:
      context: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
