version: "3"
services:
  frontend:
    build:
      context: "./client"
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - "./client:/Saloodo-Assessment/parcelTracking/client"

  backend:
    build:
      context: "./server"
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - "./server:/Saloodo-Assessment/parcelTracking/server"
